# @package _global_

embed: 
  name: state-action
  latent_dim: 256
  hidden_dim: 256
  hidden_depth: 2
  obs_dim: ???
  action_dim: ???
  activation: ???
  lr: 0.001
  batch_size: 1028
  eval_batch_size: 256
  shuffle_rate: 0.1
  train_steps: 1000000
  random_dataset: ???
  train_dataset: ???
  eval_dataset: ???
  num_demos: ???
  log_interval: 500
  eval_interval: 5000
  max_horizon: 10